---
title: "401 Project Decision Trees"
author: "Grace Lock"
date: "April 2024"
output:
  html_document:
    df_print: paged
---

```{r}
library(haven) #Reading in the data
library(dplyr)
library(tidyverse)
library(rpart) #Decision Tree
library(rpart.plot)
library(C50) #nonbinary decision tree
library(randomForest) #random forest decision tree
```

## Skintone data

```{r}
skintonedata <- read_sav("/users/PDNU0015/gracelock1/Skin IAT.public.2023 2.sav")

skintonedata |>  select("session_id", "birthyear", "birthSex", "politicalid_7",
                                 "num_002", "ethnicityomb", "raceomb_002", "edu", "D_biep.LightSkin_Good_all", 
                                 "att7", "Tdark", "Tlight") |>
                 na.omit("D_biep.LightSkin_Good_all") |>
                 rename("num_tests" = "num_002",
                        "ethnicity" = "ethnicityomb",
                        "race" = "raceomb_002",
                        "politicalid" = "politicalid_7",
                        "skintone_preference" = "att7",
                        "warmth_dark" = "Tdark",
                        "warmth_light" = "Tlight",
                        "score" = "D_biep.LightSkin_Good_all") |>
                 mutate(age = 2024 - birthyear) |>
                 select(-birthyear) -> skintonedata
```

```{r}
#Create categories 
breaks <- c(-Inf, -0.0001, 0.001, 0.33, 0.66, Inf)

skintonedata$scorecat <- cut(skintonedata$score, breaks = breaks, labels = c("Opp", "None", "Low",
                                                                             "Med", "High"))
```

```{r, fig.height= 4, fig.width=8}
#Decision Tree

# Fit the decision tree model
tree_model <- rpart(scorecat ~ num_tests + ethnicity + politicalid + skintone_preference +
                    warmth_light + age + edu + birthSex, #+ race + warmth_dark, 
                    data = skintonedata,
                    method = "class",
                    parms = list(split = "information"))

# Visualize the decision tree
rpart.plot(tree_model, type = 5, extra = 4, main = "Skintone Based Bias Decision Tree")
```

```{r}
#Train and test data 

set.seed(123)

train_indices <- sample(1:nrow(skintonedata), 0.8 * nrow(skintonedata))
test_indices <- setdiff(1:nrow(skintonedata), train_indices)

# Split the data into training and testing sets
train_data <- skintonedata[train_indices, ]
test_data <- skintonedata[-train_indices, ]
```

```{r}
#Random forest tree 

# Fit random forest model
rf_model <- randomForest(scorecat ~ num_tests + ethnicity + politicalid +
                           skintone_preference + warmth_light + age + edu + 
                           birthSex + race + warmth_dark, 
                    data = train_data, ntree = 500) 
    # You can adjust the number of trees (ntree) as needed
summary(rf_model)
```

```{r}
# Make predictions
predictions <- predict(rf_model, newdata = test_data)

conf_matrix <- table(test_data$scorecat, predictions)

conf_matrix
```

## Gender Data

```{r}
genderdata <- read_sav("/users/PDNU0015/gracelock1/Gender-Career IAT.public.2023.sav")

genderdata |> dplyr::select("session_id", "birthyear", "num_002", "birthSex", "ethnicityomb", "edu",
                     "raceomb_002", "D_biep.Male_Career_all", "impcareer", "impfamily", "politicalid_7") |> 
              na.omit("D_biep.Male_Career_all") |>
              rename("num_tests" = "num_002",
                     "ethnicity" = "ethnicityomb",
                     "race" = "raceomb_002",
                     "politicalid" = "politicalid_7",
                     "score" = "D_biep.Male_Career_all",
                     "att_family" = "impfamily",
                     "att_carerr" = "impcareer") |>
              mutate(age = 2024 - birthyear) |> 
              dplyr::select(-birthyear) -> genderdata
```

```{r}
#Create categories 
breaks <- c(-Inf, -0.0001, 0.001, 0.33, 0.66, Inf)

genderdata$scorecat <- cut(genderdata$score, breaks = breaks, labels = c("Opp", "None", "Low",
                                                                             "Med", "High"))
```

```{r, fig.height= 4, fig.width=8}
#Decision Tree

# Fit the decision tree model
tree_model <- rpart(scorecat ~ num_tests + ethnicity + politicalid
                           + age + edu + birthSex + race + att_family + att_carerr, 
                    data = genderdata,
                    method = "class",
                    parms = list(split = "information"))

# Visualize the decision tree
rpart.plot(tree_model, type = 5, extra = 4, main = "Gender Based Bias Decision Tree", box.palette = "Blues")
```

## Sexuality Data

```{r}
sexualitydata <- read_sav("/users/PDNU0015/gracelock1/Sexuality IAT.public.2023.sav")

sexualitydata |> dplyr::select("session_id", "birthyear", "num_002", "birthSex", "ethnicityomb", "edu",
                     "raceomb_002", "D_biep.Straight_Good_all", "Tgayleswomen", "Tgaymen", "Tstraightmen",
                     "politicalid_7") |>
                na.omit("D_biep.Straight_Good_all") |>
                mutate(age = 2024-birthyear) |> 
                dplyr::select(-birthyear) |> 
                rename("num_tests" = "num_002",
                      "ethnicity" = "ethnicityomb",
                      "race" = "raceomb_002",
                      "politicalid" = "politicalid_7",
                      "score" = "D_biep.Straight_Good_all",
                      "warmth_gayleswomen" = "Tgayleswomen",
                      "warmth_gaymen" = "Tgaymen",
                      "warmth_straightmen" = "Tstraightmen") -> sexualitydata
```

```{r}
#Create categories 
breaks <- c(-Inf, -0.0001, 0.001, 0.33, 0.66, Inf)

sexualitydata$scorecat <- cut(sexualitydata$score, breaks = breaks, labels = c("Opp", "None", "Low",
                                                                             "Med", "High"))
```

```{r, fig.height= 4, fig.width=8}
#Decision Tree

# Fit the decision tree model
tree_model <- rpart(scorecat ~ num_tests + ethnicity + politicalid + age + edu + 
                           birthSex + race + warmth_gayleswomen + warmth_gaymen + warmth_straightmen, 
                    data = sexualitydata,
                    method = "class",
                    parms = list(split = "information"))

# Visualize the decision tree
rpart.plot(tree_model, type = 5, extra = 4, main = "Sexuality Based Bias Decision Tree")
```

## Weight Data

```{r}
weightdata <- read_sav("/users/PDNU0015/gracelock1/Weight IAT.public.2023.sav")

weightdata |> dplyr::select("session_id", "birthyear", "num_002", "birthSex", "ethnicityomb", "edu",
                            "politicalid_7", "raceomb_002", "D_biep.Thin_Good_all", "att7", "tthin", 
                            "tfat", "comptomost_001") |>
              na.omit("D_biep.Thin_Good_all") |>
              mutate(age = 2024-birthyear) |> 
              dplyr::select(-birthyear) |> 
              rename("num_tests" = "num_002",
                      "ethnicity" = "ethnicityomb",
                      "race" = "raceomb_002",
                      "score" = "D_biep.Thin_Good_all",
                      "body_preference" = "att7",
                      "warmth_thin" = "tthin",
                      "warmth_fat" = "tfat",
                      "comptomost" = "comptomost_001",
                      "politicalid" = "politicalid_7") -> weightdata
```

```{r}
#Create categories 
breaks <- c(-Inf, -0.0001, 0.001, 0.33, 0.66, Inf)

weightdata$scorecat <- cut(weightdata$score, breaks = breaks, labels = c("Opp", "None", "Low",
                                                                             "Med", "High"))
```

```{r, fig.height= 4, fig.width=8}
#Decision Tree

# Fit the decision tree model
tree_model <- rpart(scorecat ~ num_tests + ethnicity + politicalid + age + edu + 
                           birthSex + race + warmth_thin + warmth_fat + comptomost, 
                    data = weightdata,
                    method = "class",
                    parms = list(split = "information"))

# Visualize the decision tree
rpart.plot(tree_model, type = 5, extra = 4, main = "Weight Based Bias Decision Tree")
```
