---
title: "401_exploritory"
author: "Grace Lock"
date: "2024-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Must load in the data using the other files for this file to run. 

## Skintone data exploration

```{r}
#Population data 

#Age
skintonedata |> 
  ggplot() + 
  aes(
    x = age
  ) + 
  geom_histogram()

#Race
skintonedata |> 
  mutate(
    race = case_when(
      race == 1 ~ "White",
      race == 2 ~ "Not White"
    ) ) |>
  ggplot() + 
  aes(
    x = race
  ) + 
  geom_bar() 

#Number of tests
skintonedata |> 
  ggplot() + 
  aes(
    x = num_tests
  ) + 
  geom_histogram()

#Political Identification
skintonedata |> 
  mutate(
    politicalid = frcode(
      politicalid == 1 ~ "strongly\nconservative",
      politicalid == 2 ~ "moderately\nconservative",
      politicalid == 3 ~ "slightly\nconservative",
      politicalid == 4 ~ "neutral",
      politicalid == 5 ~ "slightly\nliberal",
      politicalid == 6 ~ "moderately\nliberal",
      politicalid == 7 ~ "strongly\nliberal"
    )
  ) |>
  ggplot() + 
  aes(
    x = politicalid
  ) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Education
skintonedata |>
  mutate(
    edu = frcode(
      edu %in% c(1, 2, 3) ~ "less than high school",
      edu == 4 ~ "high school graduate",
      edu == 5 ~ "some college",
      edu == 6 ~ "associate's degree",
      edu == 7 ~ "bachelor's degree",
      edu %in% c(8, 9, 10, 11, 12, 13, 14) ~ "higher education"
    )
  ) |>
  ggplot() + 
  aes(
    x = edu
  ) + 
  geom_bar()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Sex
skintonedata |> 
  mutate(
    birthSex = case_when(
      birthSex == 1 ~ "Male",
      birthSex == 2 ~ "Female"
    )
  ) |>
  ggplot() +
  aes(
    x = birthSex
  ) + 
  geom_bar()

#Skin tone Preference
skintonedata |> 
  mutate(
    skintone_preference = frcode(
      skintone_preference == 1 ~ "strongly prefer\nDark Skinned People",
      skintone_preference == 2 ~ "moderately prefer\nDark Skinned People",
      skintone_preference == 3 ~ "slightly prefer\nDark Skinned People",
      skintone_preference == 4 ~ "I like Light Skinned People and\nDark\nSkinned People equally",
      skintone_preference == 5 ~ "slightly prefer\nLight Skinned People",
      skintone_preference == 6 ~ "moderately prefer\nLight Skinned People",
      skintone_preference == 7 ~ "strongly prefer\nLight Skinned People"
    )
  ) |> 
  ggplot() + 
  aes(
    x = skintone_preference
  ) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Score Distributions
```{r}
#Score means
mean(skintonedata$score)
mean(genderdata$score)
mean(sexualitydata$score)
mean(weightdata$score)

#Score SDs
sd(skintonedata$score)
sd(genderdata$score)
sd(sexualitydata$score)
sd(weightdata$score)
```

```{r}
skintonedata$dataset <- "Skin tone based bias"
genderdata$dataset <- "Gender based bias"
sexualitydata$dataset <- "Sexuality based bias"
weightdata$dataset <- "Weight based bias"

new_skin_df <- skintonedata[, c("session_id", "score", "dataset")]
new_gender_df <- genderdata[, c("session_id", "score", "dataset")]
new_sex_df <- sexualitydata[, c("session_id", "score", "dataset")]
new_weight_df <- weightdata[, c("session_id", "score", "dataset")]

combined_df <- rbind(new_skin_df, new_gender_df, new_sex_df, new_weight_df)

mean_values <- aggregate(score ~ dataset, data = combined_df, FUN = mean)

ggplot(combined_df, aes(x = score)) +
  geom_histogram(color = "black") +  
  facet_wrap(~ dataset, nrow = 2) +  # Facet wrap by the 'dataset' column
  ggtitle("Bias Score Distributions") +
  xlab("IAT Bias Score (d-score)") +
  ylab("Number of Participants") + 
  labs(
    caption = "Red line indicates the mean of the distribution."
  ) +
  geom_vline(data = mean_values, aes(xintercept = score), color = "red") + 
  theme_minimal()
```

## Gender data exploration 

```{r}
#Population data 

#Age
genderdata |> 
  ggplot() + 
  aes(
    x = age
  ) + 
  geom_histogram()

#Race
genderdata |> 
  mutate(
    race = case_when(
      race == 1 ~ "White",
      race == 2 ~ "Not White"
    ) ) |>
  ggplot() + 
  aes(
    x = race
  ) + 
  geom_bar() 

#Number of tests
genderdata |> 
  ggplot() + 
  aes(
    x = num_tests
  ) + 
  geom_histogram()

#Political Identification
genderdata |> 
  mutate(
    politicalid = frcode(
      politicalid == 1 ~ "strongly\nconservative",
      politicalid == 2 ~ "moderately\nconservative",
      politicalid == 3 ~ "slightly\nconservative",
      politicalid == 4 ~ "neutral",
      politicalid == 5 ~ "slightly\nliberal",
      politicalid == 6 ~ "moderately\nliberal",
      politicalid == 7 ~ "strongly\nliberal"
    )
  ) |>
  ggplot() + 
  aes(
    x = politicalid
  ) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Education
genderdata |>
  mutate(
    edu = frcode(
      edu %in% c(1, 2, 3) ~ "less than high school",
      edu == 4 ~ "high school graduate",
      edu == 5 ~ "some college",
      edu == 6 ~ "associate's degree",
      edu == 7 ~ "bachelor's degree",
      edu %in% c(8, 9, 10, 11, 12, 13, 14) ~ "higher education"
    )
  ) |>
  ggplot() + 
  aes(
    x = edu
  ) + 
  geom_bar()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Sex
genderdata |> 
  mutate(
    birthSex = case_when(
      birthSex == 1 ~ "Male",
      birthSex == 2 ~ "Female"
    )
  ) |>
  ggplot() +
  aes(
    x = birthSex
  ) + 
  geom_bar()
```



## Sexuality data exploration 

```{r}
#Population data 

#Age
sexualitydata |> 
  ggplot() + 
  aes(
    x = age
  ) + 
  geom_histogram()

#Race
sexualitydata |> 
  mutate(
    race = case_when(
      race == 1 ~ "White",
      race == 2 ~ "Not White"
    ) ) |>
  ggplot() + 
  aes(
    x = race
  ) + 
  geom_bar() 

#Number of tests
sexualitydata |> 
  ggplot() + 
  aes(
    x = num_tests
  ) + 
  geom_histogram()

#Political Identification
sexualitydata |> 
  mutate(
    politicalid = frcode(
      politicalid == 1 ~ "strongly\nconservative",
      politicalid == 2 ~ "moderately\nconservative",
      politicalid == 3 ~ "slightly\nconservative",
      politicalid == 4 ~ "neutral",
      politicalid == 5 ~ "slightly\nliberal",
      politicalid == 6 ~ "moderately\nliberal",
      politicalid == 7 ~ "strongly\nliberal"
    )
  ) |>
  ggplot() + 
  aes(
    x = politicalid
  ) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Education
sexualitydata |>
  mutate(
    edu = frcode(
      edu %in% c(1, 2, 3) ~ "less than high school",
      edu == 4 ~ "high school graduate",
      edu == 5 ~ "some college",
      edu == 6 ~ "associate's degree",
      edu == 7 ~ "bachelor's degree",
      edu %in% c(8, 9, 10, 11, 12, 13, 14) ~ "higher education"
    )
  ) |>
  ggplot() + 
  aes(
    x = edu
  ) + 
  geom_bar()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Sex
sexualitydata |> 
  mutate(
    birthSex = case_when(
      birthSex == 1 ~ "Male",
      birthSex == 2 ~ "Female"
    )
  ) |>
  ggplot() +
  aes(
    x = birthSex
  ) + 
  geom_bar()
```


## Weight data exploration 

```{r}
#Population data 

#Age
weightdata |> 
  ggplot() + 
  aes(
    x = age
  ) + 
  geom_histogram()

#Race
weightdata |> 
  mutate(
    race = case_when(
      race == 1 ~ "White",
      race == 2 ~ "Not White"
    ) ) |>
  ggplot() + 
  aes(
    x = race
  ) + 
  geom_bar() 

#Number of tests
weightdata |> 
  ggplot() + 
  aes(
    x = num_tests
  ) + 
  geom_histogram()

#Political Identification
weightdata |> 
  mutate(
    politicalid = frcode(
      politicalid == 1 ~ "strongly\nconservative",
      politicalid == 2 ~ "moderately\nconservative",
      politicalid == 3 ~ "slightly\nconservative",
      politicalid == 4 ~ "neutral",
      politicalid == 5 ~ "slightly\nliberal",
      politicalid == 6 ~ "moderately\nliberal",
      politicalid == 7 ~ "strongly\nliberal"
    )
  ) |>
  ggplot() + 
  aes(
    x = politicalid
  ) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Education
weightdata |>
  mutate(
    edu = frcode(
      edu %in% c(1, 2, 3) ~ "less than high school",
      edu == 4 ~ "high school graduate",
      edu == 5 ~ "some college",
      edu == 6 ~ "associate's degree",
      edu == 7 ~ "bachelor's degree",
      edu %in% c(8, 9, 10, 11, 12, 13, 14) ~ "higher education"
    )
  ) |>
  ggplot() + 
  aes(
    x = edu
  ) + 
  geom_bar()  +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Sex
weightdata |> 
  mutate(
    birthSex = case_when(
      birthSex == 1 ~ "Male",
      birthSex == 2 ~ "Female"
    )
  ) |>
  ggplot() +
  aes(
    x = birthSex
  ) + 
  geom_bar()
```


```{r}
Skintone = c(1.02, 1.12, 0.92, 1.02, 0.85, 0.93, NA, 1.00, 1.48, NA)
Skin_sig = c(99.9, 99.9, 99.9, 99.9, 99.9, 99, NA, 0, 99.9, NA)
Gender = c(1.02, 1.01, 0.95, 1.01, 0.94, 1.67, 0.81, 1.11, 0.93, NA)
Gender_sig = c(99.9, 0, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, NA)
Sexuality = c(1.01, 1.01, 0.77, 1.01, 0.93, 0.74, 1.21, 0.89, 0.89, 1.23)
Sex_sig = c(99, 0, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9)
Weight = c(1.00, NA, 0.91, 1.01, 0.76, 0.86, 0.80, 1.12, 0.88, 0.87)
Weight_sig = c(0, NA, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9, 99.9)

row_labels <- c("Education", "Ethnicity", "Political Identity", "Age", "Number of Tests", 
                "Sex", "Race", "Warmth1", "Warmth2", "Warmth3")

viz_data <- data.frame(Skintone, Skin_sig, Gender, Gender_sig, Sexuality, Sex_sig, Weight, Weight_sig)
rownames(viz_data) <- row_labels

# Add row names as a separate column
viz_data$row_names <- rownames(viz_data)

# Pivot the data into longer format
pivot1_df <- dplyr::select(viz_data, row_names, Skintone, Gender, Sexuality, Weight) |>
                 pivot_longer(
                           cols = -row_names,
                           names_to = "BiasType",
                           values_to = "Value") -> pivot1_df

pivot2_df <- dplyr::select(viz_data, row_names, Skin_sig, Sex_sig, Gender_sig, Weight_sig) |>
  pivot_longer(
    cols = -row_names, 
    names_to = "BiasType",
    values_to = "Significance"
  ) |> 
  mutate(
    BiasType = case_when(
      BiasType == "Skin_sig" ~ "Skintone",
      BiasType == "Gender_sig" ~ "Gender",
      BiasType == "Sex_sig" ~ "Sexuality",
      BiasType == "Weight_sig" ~ "Weight"
    )
  ) -> pivot2_df

merged_data <- merge(x = pivot1_df, y = pivot2_df, by = c("BiasType", "row_names"))

merged_data
```


```{r, warning = FALSE}
# Convert the variable to a factor with levels 0, 1, 2, and 3
merged_data$Significance <- factor(merged_data$Significance, levels = c(0, 95, 99, 99.9))

# Define colors for each level
colors <- c("gray", "blue", "green", "orange")  # You can customize the colors as needed

# Plot with ggplot
merged_data |>
  ggplot() + 
  aes(
    y = Value, 
    x = row_names,
    fill = Significance  # Use fill aesthetic for color
  ) + 
  geom_segment(aes(x=row_names, xend=row_names, y=1, yend=Value), color="grey") +
  geom_point(size=3, shape = 21) +  # Use shape 21 for filled points
  scale_fill_manual(values = colors) +  # Use manual scale for colors
  theme_light() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank(),
    axis.ticks.x = element_blank()
  ) + 
  geom_hline(yintercept = 1, linetype = "dashed", color = "black") +
  facet_wrap(~BiasType) +
  theme(
    axis.text.x = element_text(angle = 35, hjust = 1)
  ) + 
  labs(
    title = "Logistic Regression Odds Ratio with Significance by Bias Type",
    x = "Demographics",
    y = "Odds Ratio",
    fill = "Significance Level"
  )+
  theme(legend.position = "bottom") 
```










